### ISSUE TITLE
노선 겹침으로 생긴 열차 이동 버그

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Poly-Metro#360]
- 노선이 겹칠 때 나중에 만든 노선을 따라 움직이는 열차(녹색)은 해당 정거장에서 멈추고 이동하지 않습니다.
- 기존 노선(파랑)은 편집하지 않았고 위 버그가 일어난 상황에서 기존 열차(파랑)가 후에 만들어진 열차(녹색)와 만난 후 기존 열차가 이상한 곳으로 이동이 됩니다.

![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/491d2fcf-8a8a-4272-b55a-58a0283e2f09)
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/948100a5-36e2-4503-9991-703833fffda8)

**Comment by seong0929** [comment]
해당 버그가 일어난 조건에 대해 자세히 설명하겠습니다.
1. 파란 노선을 아래에서 위로 건설하였습니다.
2. 파란 열차가 아래에서 위로 올라갔습니다.
3. 올라간 사이 녹색 노선을 연결합니다.
4. 녹색 열차가 환승역에서 더 이상 움직이지 않습니다.
5. 파란 열차가 내려옵니다.
6. 파란 열차가 녹색 열차와 만납니다.
7. 파란 열차는 회전을 하며 경로를 이탈합니다.

**Comment by mille-feu** [comment]
수정되었습니다.
