### ISSUE TITLE
lua  API 코딩 버그

### ISSUE THREAD

**Issue by seong0929** [Tiny-Metro/Poly-Metro#370]
develop-InvestLua 에서 작업 중입니다.

- DestroyStation()가 안됩니다.
  - pull 받아도, Content>Script>Event>SavedSeoul 삭제해도 되지 않습니다.
  - 해당 함수 작동 시 언리얼 엔진이 멈춥니다.
- GetLaneStatistics()가 안됩니다.
  -  아래와 같은 선언부나 불러오는 과정에서 오류가 나옵니다.
    - local cur_lane_count = GetLaneStatistics()
    - local cur_lane = GetLaneStatistics()
    - cur_lane .TotalLaneCount
- GetTrainInfosAtStart()가 안됩니다.
  - 마찬다지로 선언부에서 오류가 나옵니다.
     - local start_train = GetTrainInfosAtStart(1004)

**Comment by seong0929** [comment]
밤 늦게 이슈를 올려 질문을 이 곳에 적어둡니다.
- GetStationInfos()의 ServiceLaneCount는 여러 노선이 지나가는 경우 리스트로 갖는 가요?

**Comment by ruru14** [comment]
- 버그 픽스 후 빌드는 하셨나요?
- 1004 에러 코드가 다음으로 추측됩니다.
Line 34::```if i<= start_train then```
start_train은 정수가 아닙니다.

**Comment by seong0929** [comment]
- 윗 문제는 해결되었습니다.
- [GetStationInfos()](https://github.com/Tiny-Metro/Tiny-Metro/wiki/Mod-scripting-guide-:-%EA%B0%9C%EC%9A%94-%EB%B0%8F-API#getstationinfos)의 사용 방법에 문제가 있는 듯 합니다.
  - Foo[0].Id 와 같이 인덱스를 사용하면 nil 오류가 뜹니다.
  - Foo.Id을 출력할 경우 nil이 출력됩니다.
  - 이전에 알려준 코드는 0.0만 출력합니다.
<code>
<pre>
stations = GetStationInfos()
for i, v in pairs(stations) do
    print(v.Complain) 
end
</code>
</pre>

- 아래는 테스트 돌린 코드 입니다.
<pre>
<code>
local n_test = 0

function TestFunction()
    stations = GetStationInfos()
    print(stations.Id)        -- print(stations[0].Id)
    n_test = n_test + 1
    for i, v in pairs(stations) do
        print(v.Complain) 
    end
    print(n_test)
end

return 1
</code>
</pre>
- print(stations.Id) 인 경우 로그
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/0623fb80-1f64-437b-b011-eaf9b93171cb)
- print(stations[0].Id)인 경우 로그
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/dde75b29-7c89-480f-8236-dbe4efd7e57a)

**Comment by ruru14** [comment]
- Foo[0].Id 와 같이 인덱스를 사용하면 nil 오류가 뜹니다.
- 구체적인 예시가 필요합니다.

그 외에 다른 문제 없어보입니다.

**Comment by seong0929** [comment]
- 그럼 아래 예시 처럼 사용할 수 없나요?
![image](https://github.com/Tiny-Metro/Tiny-Metro/assets/50050003/34cd9c68-2ad3-48a3-b61c-bbbc6d7e432d)

- Investment.1003에서 이전에 알려준 방식대로 실행 시 오류가 발생하지 않지만, 성공도 되지 않습니다.
- 그래서 수정을 하고 싶은 데 문서를 참고한 방식대로 "for i = 0, #stations do \n station[i].Complain"을 사용 시 에러가 나와 문제입니다. 
<pre>
<code>
function Process()
    local start_time = GetTimestampAtStart(1003)
    local cur_time = GetTimestamp()
    local stations = GetStationInfos()

    local all_stations_limit = true

    for i, v in pairs(stations) do
        if v.Complain > additional_needs_1003 then
            -- If the deadline is exceeded, it immediately fails.
            all_stations_limit = false
            break
        end
    end

    if all_stations_limit then
        if (start_time.Date - cur_time.Date) <= time_needed_1003 then
            return continue
        else
            return success
        end
    else
        return fail
    end
end
</code>
</pre>

**Comment by ruru14** [comment]
> Foo[0].Id 와 같이 인덱스를 사용하면 nil 오류가 뜹니다.
- 위 코멘트의 인용입니다.
- 구체적인 예시가 필요합니다.

> Investment.1003에서 이전에 알려준 방식대로 실행 시 오류가 발생하지 않지만, 성공도 되지 않습니다.
- 미션 로직 확인해보겠습니다.

>그래서 수정을 하고 싶은 데 문서를 참고한 방식대로 "for i = 0, #stations do \n station[i].Complain"을 사용 시 에러가 나와 문제입니다.
- 오류가 발생하는 코드가 맞습니다.
